version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest-browsers
      environment:
        - CI=true
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers
        environment:
          - CI=true
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          command: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - gem-cache-{{ arch }}-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: |
            npm install

      - save_cache:
          key: gem-cache-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Test && CodeCov
          command: npm run test && npx codecov

      - run:
          name: Build
          command: npm run build-production

      # collect reports
      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

